# Generated by Django 4.1.1 on 2022-09-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
