# Generated by Django 4.1.1 on 2022-09-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_due"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="due",
        ),
    ]
